steps:
  - label: "CPU tests"
    command:
      - "echo $JULIA_DEPOT_PATH"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"
      - "julia --project -e 'using Pkg; Pkg.test()'"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1
    timeout_in_minutes: 60

  - label: "GPU tests Julia 1.5.4"
    command:
      - "echo $JULIA_DEPOT_PATH"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.add(\"CUDA\")'"
      - "julia --project -e 'using CUDA; CUDA.versioninfo()'"
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"
      - "julia --project -e 'using Pkg; Pkg.test(;test_args=[\"CuArray\"])'"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"
    env:
      JULIA_VERSION: "1.5.4"
      CUDA_VERSION: "10.2"
    timeout_in_minutes: 60

  - wait # TODO: can we run gpu tests asynchronously?

  - label: "GPU tests Julia 1.6"
    command:
      - "echo $JULIA_DEPOT_PATH"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.add(name=\"CUDA\",version=\"3.2.1\")'"
      - "julia --project -e 'using CUDA; CUDA.versioninfo()'"
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"
      - "julia --project -e 'using Pkg; Pkg.test(;test_args=[\"CuArray\"])'"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"
    env:
      JULIA_VERSION: "1.6.0"
      CUDA_VERSION: "10.2"
    timeout_in_minutes: 60
